### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by proyb6** [Asmod4n/mruby-postgresql#1]
I haven't tried any wrapper from MRuby side compare to PHP with Postgre plugin that's tested.

How do I assure it's production ready and which Postgre version do you support?

**Comment by Asmod4n** [comment]
It should be rather stable and feature complete, i don't know if it works for your use case though.
Compatibility wise it should support every postgresql Version which is still maintained, but i haven't tested that.

I have only read the libpg documentation from those Versions still listed on the api site and took turns to support all of them, at least in theory.

**Comment by proyb6** [comment]
It’s ideal if there is a test suite in this repo with H2O web server and standalone?

**Comment by Asmod4n** [comment]
Ill try to add some tests, but is there a need to test with h2o? it just simply embeds mruby.

**Comment by proyb6** [comment]
Thank, H2O is often in rapid change which might break MRuby, that applicable to MRuby 1.4.x if they merge in the future.

**Comment by everton** [comment]
> Ill try to add some tests, but is there a need to test with h2o? it just simply embeds mruby.

It is probably the most interesting use case, no? Using mruby+h2o enables very promising experimentations (with amazing h2o response times), I came here in this post looking for alternatives to replace an existing API created with Ruby

**Comment by proyb6** [comment]
@Everton I realise you have replied to a 2 years old, I had move on from Ruby/Crystal/Nodejs/PHP to Go for the benefits of staticcheck, security and performant with zero allocation.

Good luck to your experimentation with MRuby.
